### ISSUE TITLE
Slide not available

### ISSUE THREAD

**Issue by abhinbt** [pydatabangalore/talks#19]
# Slide not available
>

##   4 |  September 21, 2019 | Text Analytics using R | Prof. Aruna Devi & Dr. Vinothina V
> 
Slide not available

**Comment by amrrs** [comment]
We're following up with the speakers for the slides. Last week they were travelling so couldn't get it. Will update at the latest !

**Comment by NirantK** [comment]
This is not a proposal. Mislabeled @vinayak-mehta. Please update

**Comment by NirantK** [comment]
@amrrs - can you please check in the speaker for slide link again? We'd really love to add them here. 

They can add the deck via Google Drive link or a [Speakerdeck](https://speakerdeck.com/) for instance

**Comment by amrrs** [comment]
Hey, checked this multiple instances. I don't think they're going to share it. So better to close this issue.

**Comment by vinayak-mehta** [comment]
:+1:

**Comment by vinayak-mehta** [comment]
Should we ask potential speakers to update their talk proposal with a slide link before accepting their talks to prevent this in the future?

**Comment by NirantK** [comment]
No, that is unfair to ask speakers. The slides isn't the point. The talk
is, and we have that on video.

**Comment by vinayak-mehta** [comment]
I know it adds an extra layer of approval but unless we sort out the video recording (with the talk slides visible on the video itself, like conferences do), not having the slides would lead to an incomplete resource, since the slides usually contain links to further reading.

It'll also help us gauge if a talk is polished or not. As mentors, we can work with potential speakers and give them pointers on how they can come with that first version of slides.

**Comment by NirantK** [comment]
I'd actually be happy to even stop recording. *Further reading *should not
be buried in the slides anyway.

For talk polish, let's do more homework on talk outline itself. And frankly
- that'd be require a much larger speaker applicant pool.
We don't have that luxury right now.

I suggest, we revisit this decision in 2 months from now? What do you think?

**Comment by vinayak-mehta** [comment]
> I suggest, we revisit this decision in 2 months from now? What do you think?

Makes sense.
